steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/ci-cd-demo-image',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ci-cd-demo-image']

- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run',
    'deploy',
    'ci-cd-demo-service',
    '--image', 'gcr.io/$PROJECT_ID/ci-cd-demo-image',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]

images:
- 'gcr.io/$PROJECT_ID/ci-cd-demo-image'

options:
  logging: CLOUD_LOGGING_ONLY